module.exports = {
  'elliptic': { algorithm: 'ECDSA (secp256k1/p256)', risk: 'critical', weight: 40, migration: 'Replace with @noble/post-quantum (Dilithium) for signatures', pqc: false },
  'secp256k1': { algorithm: 'ECDSA (secp256k1)', risk: 'critical', weight: 40, migration: 'Replace with @noble/post-quantum (Dilithium) for signatures', pqc: false },
  'ethereumjs-util': { algorithm: 'ECDSA (secp256k1)', risk: 'critical', weight: 40, migration: 'Replace with @ethereumjs/util + post-quantum signing layer', pqc: false },
  '@ethereumjs/util': { algorithm: 'ECDSA (secp256k1)', risk: 'critical', weight: 40, migration: 'Add post-quantum signing layer alongside existing ECDSA', pqc: false },
  'ethers': { algorithm: 'ECDSA (secp256k1) signing', risk: 'critical', weight: 40, migration: 'Monitor ethers.js PQC roadmap. Use hybrid approach.', pqc: false },
  'web3': { algorithm: 'ECDSA (secp256k1) signing', risk: 'critical', weight: 40, migration: 'Monitor web3.js PQC roadmap. Use hybrid approach.', pqc: false },
  'web3-eth-accounts': { algorithm: 'ECDSA (secp256k1)', risk: 'critical', weight: 40, migration: 'No direct replacement — hybrid signing approach recommended', pqc: false },
  'bitcoinjs-lib': { algorithm: 'ECDSA (secp256k1)', risk: 'critical', weight: 40, migration: 'No PQC replacement yet — monitor Bitcoin PQC proposals (BIP-360)', pqc: false },
  'node-rsa': { algorithm: 'RSA', risk: 'critical', weight: 35, migration: 'Replace with @noble/post-quantum (Kyber for KEM, Dilithium for signatures)', pqc: false },
  'jsrsasign': { algorithm: 'RSA / DSA / ECDSA', risk: 'critical', weight: 35, migration: 'Replace with @noble/post-quantum', pqc: false },
  'jsbn': { algorithm: 'RSA (big integer ops)', risk: 'critical', weight: 30, migration: 'Replace RSA operations with @noble/post-quantum (Kyber)', pqc: false },
  'node-forge': { algorithm: 'RSA / DSA (configurable)', risk: 'critical', weight: 25, migration: 'Replace RSA/DSA usage with @noble/post-quantum', pqc: false },
  'rsa-pem-to-jwk': { algorithm: 'RSA (key conversion)', risk: 'critical', weight: 30, migration: 'Replace with post-quantum key formats when ecosystem matures', pqc: false },
  'keypair': { algorithm: 'RSA key generation', risk: 'critical', weight: 35, migration: 'Replace with @noble/post-quantum (Kyber keypair generation)', pqc: false },
  'ursa': { algorithm: 'RSA (native bindings)', risk: 'critical', weight: 35, migration: 'Replace with @noble/post-quantum (Kyber)', pqc: false },
  'ursa-optional': { algorithm: 'RSA (native bindings)', risk: 'critical', weight: 35, migration: 'Replace with @noble/post-quantum (Kyber)', pqc: false },
  'ecdsa': { algorithm: 'ECDSA', risk: 'critical', weight: 40, migration: 'Replace with @noble/post-quantum (Dilithium)', pqc: false },
  'ec-key': { algorithm: 'ECDSA key handling', risk: 'critical', weight: 35, migration: 'Replace with post-quantum key handling', pqc: false },
  'eckey': { algorithm: 'ECDSA key handling', risk: 'critical', weight: 35, migration: 'Replace with post-quantum key handling', pqc: false },
  'tiny-secp256k1': { algorithm: 'ECDSA (secp256k1)', risk: 'critical', weight: 40, migration: 'Replace with @noble/post-quantum (Dilithium)', pqc: false },
  '@noble/secp256k1': { algorithm: 'ECDSA (secp256k1)', risk: 'critical', weight: 40, migration: 'Upgrade to @noble/post-quantum for PQC signatures', pqc: false },
  '@noble/curves': { algorithm: 'ECDSA (multiple curves)', risk: 'critical', weight: 40, migration: 'Upgrade to @noble/post-quantum for PQC signatures', pqc: false },
  'ethereumjs-tx': { algorithm: 'ECDSA (secp256k1) transaction signing', risk: 'critical', weight: 40, migration: 'No direct replacement — hybrid signing approach recommended', pqc: false },
  'eth-sig-util': { algorithm: 'ECDSA (secp256k1) signature utilities', risk: 'critical', weight: 40, migration: 'No direct replacement — hybrid signing approach recommended', pqc: false },
  'jsonwebtoken': { algorithm: 'RSA / ECDSA (JWT signing)', risk: 'critical', weight: 30, migration: 'Use symmetric algorithms (HS256) short-term, watch for PQC JWT RFCs', pqc: false },
  'jose': { algorithm: 'RSA / ECDSA (JOSE/JWT)', risk: 'critical', weight: 30, migration: 'Use symmetric algorithms short-term, watch for PQC JOSE support', pqc: false },
  'passport-jwt': { algorithm: 'RSA / ECDSA (JWT via jsonwebtoken)', risk: 'critical', weight: 25, migration: 'Switch to symmetric JWT signing as interim measure', pqc: false },
  'bls-signatures': { algorithm: 'BLS signatures (pairing-based)', risk: 'critical', weight: 38, migration: 'BLS is broken by quantum. Monitor IETF PQC working group for replacements.', pqc: false },
  '@chainsafe/bls': { algorithm: 'BLS signatures (pairing-based)', risk: 'critical', weight: 38, migration: 'BLS is broken by quantum. No direct drop-in yet.', pqc: false },
  'noble-bls12-381': { algorithm: 'BLS12-381 (pairing-based)', risk: 'critical', weight: 38, migration: 'Pairing-based crypto broken by quantum. Monitor for PQC replacements.', pqc: false },
  '@noble/bls12-381': { algorithm: 'BLS12-381 (pairing-based)', risk: 'critical', weight: 38, migration: 'Pairing-based crypto broken by quantum. Monitor for PQC replacements.', pqc: false },
  'mcl-wasm': { algorithm: 'BLS/pairing-based crypto (wasm)', risk: 'critical', weight: 38, migration: 'Pairing-based crypto broken by quantum. Monitor for PQC replacements.', pqc: false },
  'rainbow-sig': { algorithm: 'Rainbow (multivariate — broken 2022)', risk: 'critical', weight: 40, migration: 'Rainbow was broken in 2022. Replace with CRYSTALS-Dilithium immediately.', pqc: false },
  'gemss': { algorithm: 'GeMSS (multivariate signatures)', risk: 'critical', weight: 35, migration: 'GeMSS key sizes are impractical. Replace with CRYSTALS-Dilithium.', pqc: false },
  'md5': { algorithm: 'MD5 (broken classically)', risk: 'critical', weight: 20, migration: 'Replace with SHA-3 immediately — MD5 is broken even without quantum', pqc: false },
  'crypto-js': { algorithm: 'AES-128 / SHA-256 (configurable)', risk: 'medium', weight: 10, migration: 'Use AES-256 mode explicitly. SHA-256 acceptable with larger outputs.', pqc: false },
  'js-sha256': { algorithm: 'SHA-256', risk: 'medium', weight: 8, migration: 'Consider SHA-3 (js-sha3) for stronger quantum resistance', pqc: false },
  'js-sha3': { algorithm: 'SHA-3', risk: 'safe', weight: 0, migration: null, pqc: false },
  'aes-js': { algorithm: 'AES (key-size dependent)', risk: 'medium', weight: 10, migration: 'Ensure AES-256 is used — AES-128 is weakened by Grover\'s algorithm', pqc: false },
  'bcrypt': { algorithm: 'bcrypt (SHA-512 based)', risk: 'medium', weight: 5, migration: 'Consider Argon2 (argon2 package) for stronger quantum resistance', pqc: false },
  'bcryptjs': { algorithm: 'bcrypt (SHA-512 based)', risk: 'medium', weight: 5, migration: 'Consider Argon2 (argon2 package) for stronger quantum resistance', pqc: false },
  'sha.js': { algorithm: 'SHA-1 / SHA-256', risk: 'medium', weight: 8, migration: 'Use SHA-3 for stronger quantum resistance', pqc: false },
  'pqc-kyber': { algorithm: 'CRYSTALS-Kyber (lattice KEM)', risk: 'safe', weight: 0, migration: null, pqc: true },
  'dilithium-crystals-js': { algorithm: 'CRYSTALS-Dilithium (lattice signatures)', risk: 'safe', weight: 0, migration: null, pqc: true },
  '@noble/post-quantum': { algorithm: 'Kyber / Dilithium / SPHINCS+', risk: 'safe', weight: 0, migration: null, pqc: true },
  'sphincs': { algorithm: 'SPHINCS+ (hash-based signatures)', risk: 'safe', weight: 0, migration: null, pqc: true },
  'liboqs-node': { algorithm: 'Multiple PQC algorithms (liboqs bindings)', risk: 'safe', weight: 0, migration: null, pqc: true },
  'pqclean': { algorithm: 'Multiple PQC algorithms', risk: 'safe', weight: 0, migration: null, pqc: true },
  'ntru': { algorithm: 'NTRU (lattice-based encryption)', risk: 'safe', weight: 0, migration: null, pqc: true },
  'kyber-crystals': { algorithm: 'CRYSTALS-Kyber (KEM)', risk: 'safe', weight: 0, migration: null, pqc: true },
  'falcon-sign': { algorithm: 'FALCON (lattice signatures — NIST alternate)', risk: 'safe', weight: 0, migration: null, pqc: true },
  'sphincsplus': { algorithm: 'SPHINCS+ (hash-based — NIST standard)', risk: 'safe', weight: 0, migration: null, pqc: true },
};
