module.exports = {
  'elliptic': { algorithm: 'ECDSA (secp256k1/p256)', risk: 'critical', weight: 40 },
  'secp256k1': { algorithm: 'ECDSA (secp256k1)', risk: 'critical', weight: 40 },
  'ethereumjs-util': { algorithm: 'ECDSA (secp256k1)', risk: 'critical', weight: 40 },
  '@ethereumjs/util': { algorithm: 'ECDSA (secp256k1)', risk: 'critical', weight: 40 },
  'ethers': { algorithm: 'ECDSA (secp256k1) signing', risk: 'critical', weight: 40 },
  'web3': { algorithm: 'ECDSA (secp256k1) signing', risk: 'critical', weight: 40 },
  'bitcoinjs-lib': { algorithm: 'ECDSA (secp256k1)', risk: 'critical', weight: 40 },
  'node-rsa': { algorithm: 'RSA', risk: 'critical', weight: 35 },
  'jsrsasign': { algorithm: 'RSA / DSA / ECDSA', risk: 'critical', weight: 35 },
  'jsbn': { algorithm: 'RSA (big integer ops)', risk: 'critical', weight: 30 },
  'node-forge': { algorithm: 'RSA / DSA (configurable)', risk: 'critical', weight: 25 },
  'crypto-js': { algorithm: 'AES-128 / SHA-256 (configurable)', risk: 'medium', weight: 10 },
  'js-sha256': { algorithm: 'SHA-256', risk: 'medium', weight: 8 },
  'aes-js': { algorithm: 'AES (key-size dependent)', risk: 'medium', weight: 10 },
  'pqc-kyber': { algorithm: 'CRYSTALS-Kyber (lattice KEM)', risk: 'safe', weight: 0 },
  'dilithium-crystals-js': { algorithm: 'CRYSTALS-Dilithium', risk: 'safe', weight: 0 },
  '@noble/post-quantum': { algorithm: 'Kyber / Dilithium / SPHINCS+', risk: 'safe', weight: 0 },
  'sphincs': { algorithm: 'SPHINCS+ (hash-based signatures)', risk: 'safe', weight: 0 },
};
